description: Disable signature checks in TWL

patches:
    patch1.bin:
        type: TWL_FIRM
        versions:
            o3ds:
                0x16: 0x080238C0
                0x18: 0x080238C0
            n3ds:
                0x00: 0x08023864
                0x04: 0x08023864

    patch2.bin:
        type: TWL_FIRM
        versions:
            o3ds:
                0x16: 0x0803220E
                0x18: 0x080238C0
            n3ds:
                0x00: 0x0803224A
                0x04: 0x08023864

    patch3.bin:
        type: TWL_FIRM
        versions:
            o3ds:
                0x16: 0x08033002
                0x18: 0x080238C0
            n3ds:
                0x00: 0x0803303E
                0x04: 0x08023864

    patch4.bin:
        type: TWL_FIRM
        versions:
            o3ds:
                0x16: 0x08033656
                0x18: 0x080238C0
            n3ds:
                0x00: 0x08033692
                0x04: 0x08023864
