description: Disable signature checks in AGB

patches:
    patch.bin:
        type: AGB_FIRM
        versions:
            o3ds:
                0x0B: 0x080182A8
            n3ds:
                0x00: 0x08018164
